### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by javierguerragiraldez** [ziglibs/repository#36]
any project listing would need at the very least:
- link to project page
- link to documentation
- option to non-git repositories

**Comment by MasterQ32** [comment]
Feel free to implement that, especially as not every project has a project page nor documentation

**Comment by MasterQ32** [comment]
That sounds like a cool idea, looking forward to it! I might also have some additions which we can try implementing.

**Comment by javierguerragiraldez** [comment]
funny.
the original issue was "lets make it more useful for non-github packages" (and maybe someday for non-git too)
first answer: "not interested"

side comment: "lets add some github-dependent feature"  "fixed"
